--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 1, OK! Considerado: 100.0%.
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 2, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 3, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 4, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 5, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 6, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 7, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 8, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 9, OK! Considerado: 100.0%. 
--- Atividade 'A1_2': Instância fln_pequena.net sobre o vértice 10, OK! Considerado: 100.0%. 

--- Um erro ocorreu ao tentar executar o arquivo 'A1_2' de sua atividade. [invalid literal for int() with base 10: 
    'Traceback (most recent call last)'][Traceback (most recent call last): File "A1_2.py", line 30, in <module> main()
    File "A1_2.py", line 13, in main graph = Graph(sys.argv[1]) File "/home/p10735/grafo.py", 
    line 6, in __init__ self.ler(arquivo) File "/home/p10735/grafo.py", line 37, in
     ler u, v, w = map(int, line.split()) ValueError: invalid literal for int() with base 10: '1.0'] 